version: '3.12'

services:
  web-app:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/src
    command: uvicorn src.main:app --port 8000 --host 0.0.0.0
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: db_app
    env_file:
      - .env